### PR TITLE
USWDS - Validation: Adds complete/incomplete labels for screen readers. Resolves #4477

### LINKED ISSUE #4477: Validation: Add Aria-Label for Checked/Not Checked (508)
### Describe the bug
The checkmarks that display next to each met requirement is the only communication that the user has/hasn't met the given requirements. Users who are blind or visually impaired will rely on screen readers to convey the meaning behind the checkmarks (or lack of). I would recommend adding an aria-label to each list item that communicates the status of each requirement.

Something like (using the example shown in the screenshot):
`aria-label="Use at least one uppercase character (Checked)"`
or
`aria-label="Use at least one number (Not Checked)"`

### Steps to reproduce the bug
1. Navigate to feature using Validation component
2. Listen to what is read aloud by a screenreader (e.g. on mac, VoiceOver)
  - Notice - no context is given about what is checked or not checked

### Expected behavior
Screen readers should read the content of the Validation component, communicating with the user which items have met requirements and which have not.

### Screenshots
Screen Shot 2022-01-24 at 4 46 54 PM
Screen Shot 2022-01-24 at 4 47 58 PM

### PR DESCRIPTION
**Pull request by mahoneycm**
## Preview

[Validation →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/cm-validation-a11y/?path=/story/components-validation--validation)

## Description

Upon initialization, a new span is created for validation checklist items with the `usa-sr-only` class and a `data-checklist-label=hidden` data attribute. By default the span is set to "Incomplete"

When the validator updates the items to "checked", it will change the text content to `Complete` or `Incomplete` as necessary. 

Resolves #4477 

## Additional information

This PR also changes the validation event listener from `keyup change` to `input change` so that keys like shift wouldn't trigger the function

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

File: packages/usa-validation/src/index.js [hunk 1]
```diff
@@ -1,14 +1,47 @@
...
+    init(root) {
+      selectOrMatches(VALIDATE_INPUT, root).forEach((item) => {
+        const validationParent = item.parentNode;
+        const checklistItems =
+          validationParent.querySelectorAll(CHECKLIST_ITEM);
+
+        checklistItems.forEach((listItem) => {
+          const newSpan = createHiddenLabel();
+          listItem.appendChild(newSpan);
+          listItem.setAttribute("aria-live", "polite");
```
Comment (mejiaj) [inline packages/usa-validation/src/index.js:39]: Can we move `aria-live` and `aria-atomic` to the parent `ul` element?

File: packages/usa-validation/src/index.js [hunk 2]
```diff
@@ -1,14 +1,47 @@
...
+  {
+    "input change": {
+      [VALIDATE_INPUT]: change,
+    },
   },
-});
+  {
+    init(root) {
+      selectOrMatches(VALIDATE_INPUT, root).forEach((item) => {
+        const validationParent = item.parentNode;
```
Comment (mejiaj) [inline packages/usa-validation/src/index.js:32]: Since the input now controls the checklist, it might make sense to try adding `aria-controls=""` and point to the checklist `ID`.

**Review by mejiaj — CHANGES_REQUESTED** [review]
Nice work! Just a few changes.

Can we remove the `usa-checklist__item--checked` from `usa-validation.twig:8` so it shows the correct initial state?

File: packages/usa-validation/src/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (mahoneycm) [reply packages/usa-validation/src/index.js]: Resolved in [23a5c3f](https://github.com/uswds/uswds/pull/4719/commits/23a5c3f55d886c5437f123235922d7f1cb4c98d7)

File: packages/usa-validation/src/index.js (hunk 2 above)
Comment (mahoneycm) [reply packages/usa-validation/src/index.js:33]: Resolved in [23a5c3f](https://github.com/uswds/uswds/pull/4719/commits/23a5c3f55d886c5437f123235922d7f1cb4c98d7)

**Review by mejiaj — APPROVED** [review]

**Comment by mejiaj** [comment]
Placing `hold` so we can get additional a11y testing and feedback.

**Comment by brunerae** [comment]
@thisisdano this is ready for final review!

File: packages/usa-validation/src/test/template.html [hunk 3]
```diff
@@ -1,15 +1,24 @@
...
-    id="password" name="password" type="password"
+    id="password"
+    name="password"
+    type="password"
     aria-describedby="validation_list"
     data-validate-length=".{8,}"
     data-validate-uppercase="[A-Z]"
     data-validate-numerical="\d"
-    data-validation-element="validation_list">
+    data-validation-element="#validation_list"
```
Comment (thisisdano) [inline packages/usa-validation/src/test/template.html:22]: @mejiaj Is the `#` in the data attribute meaningful? Otherwise the markup is exactly the same?

**Review by thisisdano — COMMENTED** [review]
@mejia one comment for you: https://github.com/uswds/uswds/pull/4719/files#r931626437

File: packages/usa-validation/src/test/template.html (hunk 3 above)
Comment (thisisdano) [reply packages/usa-validation/src/test/template.html:22]:
```suggestion
    data-validation-element="validation_list"
```
