### PR TITLE
USWDS - Date picker: Prevent focus on mouseover

### LINKED ISSUE #5752: USWDS - Bug: Date picker - mouse hover preventing keyboard interaction on high zoom magnification
### Describe the bug

When testing the date picker for zoom magnification functionality, I found that at 400% and using a keyboard to select a date I was unable to use the arrow keys to move off a date. I was "stuck" on a date because my mouse was called over to that date automatically.

In essence, the mouse was jumping to focus on a date and wouldn't allow the keyboard to take control of functionality.

I was using Chrome on a PC.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/date-picker/
2. Zoom into 400% magnification
3. Try tabbing into the date picker calendar icon; tab into a date to select
4. Then try using keyboard arrow keys to move around inside the calendar. Inconsistently it works; but sometimes if the mouse is anywhere inside the browser it'll "call" the cursor over to the date and create a keyboard trap.

### Expected Behavior

Tabbing into the calendar icon and navigating using a keyboard only should never trap the keyboard focus on a date even at a high magnification like 400%

> [!CAUTION]
> **This is a AA level failure**
> The intent of this Success Criterion is to support people with low vision who need to enlarge text and read it in a single column. When the browser zoom is used to scale content to 400%, it reflows - i.e., it is presented in one column so that scrolling in more than one direction is not necessary. [^1]

[^1]: [WCAG Reflow (Level AA) requirement](https://arc.net/l/quote/qblbjcul)

### Screenshots

_No response_

### System setup

PC, Chrome

### Additional context

This type of keyboard trap inside the calendar is an issue because some low vision users use a high level of magnification and a keyboard to navigate inside components.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

**Fixed a bug that caused `mouseover` events to focus buttons and prevent keyboard navigation.** Now, hovering the mouse over date picker buttons will only cause the `hover` state.

## Breaking change

This is not a breaking change

## Related issue

Closes #5752

## Related pull requests

[Changelog →](https://github.com/uswds/uswds-site/pull/2496)

An alternative approach to #5778. This approach introduces a separate accessibility issue where screen-readers read the focused date every time a date button is hovered. This includes when a new date is selected via the keyboard while the mouse is hovering over a date. This would introduce confusion for screen reader users.

## Preview link

[Date Picker →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-date-range-remove-mouseover/?path=/story/components-form-inputs-date-picker--default)

[Date Range Picker →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-date-range-remove-mouseover/?path=/story/components-form-inputs-date-range-picker--default)

## Problem statement

Hovering the mouse over date picker calendar buttons cause them to gain focus. This is unexpected behavior which also prevents keyboard navigation through calendar buttons.

## Solution

Rework the `handleMouseoverFromDate()` function to target the date buttons of the current month and add the `--within-range` class. The function no longer calls the `renderCalendar()` function or sets focus on the hovered dates.

1. Follows expected `mouseover` behaviors.
2. Does not affect date picker or date range usage.

Additionally, I removed the `mouseover` event listeners and functions from month and year buttons. They did not appear to add any functionality beyond focusing the button on hover, which we want to prevent.

`handleMousoverFromDate` is maintained in order to properly render date range previews on hover.

### Accessibility improvements

This solution improves accessibility interaction in two ways.

**VoiceOver**

In its current iteration, when using the date picker with a mouse and VoiceOver, it would rapidly call out dates as your mouse moved over them. This, in my opinion, is unexpected behavior. VoiceOver should not read out other buttons or table content upon `mouseover` events.

With this update, VoiceOver will only call out the buttons when selected via the keyboard.

**High zoom magnification behaviors**

As depicted in #5752, using the date picker at a high magnification (400%, AA requirement) the mouse would sometimes jump to the selected button, causing a mouseover event, and locking the focus on that button. Keyboard interaction would be prevented by the hovered mouse. For users who rely on keyboard navigation, this would cause confusion as they would not move the mouse to identify the issue.

With this update, users will be able to use expected keyboard interactions without error.

### Alternatives considered

**blur**

I tested calling `blur()` on the selected element during keyboard interactions, but this caused accessibility issues at high zoom (400%). The window would jump unexpectedly and cause the mouse to move, hovering a new button, which then stole focus once again.

**Reassigning focus on render**

This was the approach taken in #5778.

I tested storing the focused button value and reapplying focus after the calendar re-rendered. Visually, this solution worked fine but caused the screen reader to call out the focused date every time the mouse hovered a new date. The date wouldn't match what is hovered and could be confusing for users if their mouse accidentally hovered over a date button.

**Removing `mouseover` events altogether**

Originally, I had removed mouseover events altogether. This caused a visual regression when selecting a date range for the first time where the range preview would not show. 

### Additional concerns

Current date picker behaviors cause a new calendar to be rendered after every mouseover and keyboard event. It does so by cloning the existing calendar, setting appropriate classes and returning an HTML template literal. This pattern does not match modern USWDS practices and likely affects performance.

## Major changes

- Date picker no longer updates focus on `mouseover` events.
- Behavior changes help to meet WCAG AA requirement
- Created a new `setRangeDates()` function to capture repeated behaviors to set range dates within the render calendar and handle mouseover functions.

> The intent of this Success Criterion is to support people with low vision who need to enlarge text and read it in a single column. When the browser zoom is used to scale content to 400%, it reflows - i.e., it is presented in one column so that scrolling in more than one direction is not necessary. [^1]
> [^1]: [WCAG Reflow (Level AA) requirement](https://arc.net/l/quote/qblbjcul)

## Testing and review

1. Visit date picker.
2. Test mouse interactions and confirm they work as expected.
3. Test keyboard interactions and confirm they work as expected.
    - **Note:** Ensure you can use keyboard navigation while the mouse is hovering a date
5. Test VoiceOver and ensure callouts are expected.
6. Zoom to 400% magnification and use the keyboard to interact with the date picker. There should be no errors navigating throughout the calendar.
7. Repeat steps for all variants.
8. Repeat steps date range picker and its variants.

> [!TIP]
> When using keyboard navigation with a screenreader, use the screenreader’s **Table Navigation** controls (varies by screenreader). This can help prevent unexpected interactions. Use default arrow keys when jumping months via dates.

### Testing checklist

- [ ]  Expected mouse behaviors work without error
- [ ]  Expected keyboard behaviors work without error
- [ ]  Screenreader behaviors work as expected without error
- [ ]  Component is usable at high magnification without error

### CODE REVIEW

**Comment by mahoneycm** [comment]
Closing in favor of #5778

**Comment by mahoneycm** [comment]
Reopening this issue due to additional accessibility errors caused by the approach taken in #5778

File: packages/usa-date-picker/src/index.js [hunk 1]
```diff
@@ -1785,24 +1816,43 @@ const handleShiftPageDownFromDate = adjustCalendar((date) => addYears(date, 1));
...
 const handleMouseoverFromDate = (dateEl) => {
   if (dateEl.disabled) return;
 
-  const calendarEl = dateEl.closest(DATE_PICKER_CALENDAR);
+  const hoverDate = parseDateString(dateEl.dataset.value);
+  const { calendarEl, selectedDate, rangeDate } = getDatePickerContext(dateEl);
 
-  const currentCalendarDate = calendarEl.dataset.value;
-  const hoverDate = dateEl.dataset.value;
+  if (selectedDate) return;
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/index.js:1831]: Returning early if there is a selected date. This allows us to match current date-range behaviors.

File: packages/usa-date-picker/src/index.js [hunk 2]
```diff
@@ -2230,12 +2248,6 @@ if (!isIosDevice()) {
     [CALENDAR_DATE_CURRENT_MONTH]() {
       handleMouseoverFromDate(this);
     },
-    [CALENDAR_MONTH]() {
-      handleMouseoverFromMonth(this);
-    },
-    [CALENDAR_YEAR]() {
-      handleMouseoverFromYear(this);
-    },
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/index.js:2238]: Removed mouseover from month and year functions because we do not want to re-render and focus these buttons on hover.

File: packages/usa-date-picker/src/test/date-picker-month-selection.spec.js [hunk 3]
```diff
@@ -153,20 +153,5 @@ tests.forEach(({ name, selector: containerSelector }) => {
...
-        ),
-      );
-
-      assert.strictEqual(
-        getCalendarEl(".usa-date-picker__calendar__month--focused").dataset
-          .label,
-        "October",
-        "focuses correct month",
-      );
-    });
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/test/date-picker-month-selection.spec.js:170]: Removed test because we are no longer setting focus when month buttons are hovered.

File: packages/usa-date-picker/src/test/date-picker-mousemove.spec.js [hunk 4]
```diff
@@ -64,32 +64,6 @@ tests.forEach(({ name, selector: containerSelector }) => {
...
-      );
-
-      assert.strictEqual(
-        getCalendarEl(".usa-date-picker__calendar__date--focused").dataset
-          .value,
-        "2020-06-19",
-        "focuses correct date",
-      );
-    });
-
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/test/date-picker-mousemove.spec.js:92]: Removed test because we are no longer setting focus when date buttons are hovered.

File: packages/usa-date-picker/src/test/date-picker-year-selection.spec.js [hunk 5]
```diff
@@ -151,20 +151,5 @@ tests.forEach(({ name, selector: containerSelector }) => {
...
-        ),
-      );
-
-      assert.strictEqual(
-        getCalendarEl(".usa-date-picker__calendar__year--focused").dataset
-          .value,
-        "2022",
-        "focuses correct year",
-      );
-    });
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/test/date-picker-year-selection.spec.js:168]: Removed test because we are no longer setting focus when year buttons are hovered.

File: packages/usa-date-picker/src/index.js [hunk 6]
```diff
@@ -1785,24 +1816,43 @@ const handleShiftPageDownFromDate = adjustCalendar((date) => addYears(date, 1));
...
+      isDateWithinMinAndMax(
+        buttonDate,
+        withinRangeStartDate,
+        withinRangeEndDate,
+      )
+    ) {
+      button.classList.add(CALENDAR_DATE_WITHIN_RANGE_CLASS);
+    } else {
+      button.classList.remove(CALENDAR_DATE_WITHIN_RANGE_CLASS);
+    }
```
Comment (mahoneycm) [inline packages/usa-date-picker/src/index.js:1854]: For each date button in the current calendar month, check if it's value is within the date range.

If it is, add the `within range` class. If itis not, remove it.

File: packages/usa-date-picker/src/index.js [hunk 7]
```diff
@@ -464,6 +464,37 @@ const isDatesYearOutsideMinOrMax = (date, minDate, maxDate) =>
   lastDayOfMonth(setMonth(date, 11)) < minDate ||
   (maxDate && startOfMonth(setMonth(date, 0)) > maxDate);
 
+/**
+ * @typedef {Object} DateRangeContext
+ * @property {Date} rangeStartDate
+ * @property {Date} rangeEndDate
+ * @property {Date} withinRangeStartDate
+ * @property {Date} withinRangeEndDate
+ */
```
Comment (mejiaj) [inline packages/usa-date-picker/src/index.js:473]: **praise:** Thanks for adding this, I see the definitions on hover in VS Code.

image

File: packages/usa-date-picker/src/index.js [hunk 8]
```diff
@@ -1785,24 +1816,43 @@ const handleShiftPageDownFromDate = adjustCalendar((date) => addYears(date, 1));
 const handleShiftPageUpFromDate = adjustCalendar((date) => subYears(date, 1));
 
 /**
- * display the calendar for the mouseover date.
+ * Set range date classes without re-rendering the calendar. Called when date button is hovered.
+ * Returns early if the date hovered is disabled or if there is a selected date already.
```
Comment (mejiaj) [inline packages/usa-date-picker/src/index.js:1820]: **quibble:** Small copy change for clarity.

```suggestion
 * Returns early if the date hovered is disabled or if there is already a selected date.
```

File: packages/usa-date-picker/src/index.js [hunk 9]
```diff
@@ -1785,24 +1816,43 @@ const handleShiftPageDownFromDate = adjustCalendar((date) => addYears(date, 1));
...
  *
- * @param {MouseEvent} event The mouseover event
- * @param {HTMLButtonElement} dateEl A date element within the date picker component
+ * @param {HTMLElement} dateEl - Calendar date button within the date picker component.
  */
+
 const handleMouseoverFromDate = (dateEl) => {
   if (dateEl.disabled) return;
 
-  const calendarEl = dateEl.closest(DATE_PICKER_CALENDAR);
```
Comment (mejiaj) [inline packages/usa-date-picker/src/index.js:1796]: **question:** Is this check happening somewhere else or no longer needed?

File: packages/usa-date-picker/src/index.js [hunk 10]
```diff
@@ -1785,24 +1816,43 @@ const handleShiftPageDownFromDate = adjustCalendar((date) => addYears(date, 1));
...
+  const { withinRangeStartDate, withinRangeEndDate } = setRangeDates(
+    hoverDate,
+    rangeDate,
+  );
 
-  const dateToDisplay = parseDateString(hoverDate);
-  const newCalendar = renderCalendar(calendarEl, dateToDisplay);
-  newCalendar.querySelector(CALENDAR_DATE_FOCUSED).focus();
+  const dateButtons = calendarEl.querySelectorAll(
+    `.${CALENDAR_DATE_CURRENT_MONTH_CLASS}`,
```
Comment (mejiaj) [inline packages/usa-date-picker/src/index.js:1839]: **question:** Is the comma needed here?

```suggestion
    `.${CALENDAR_DATE_CURRENT_MONTH_CLASS}`
```

**Review by mejiaj — COMMENTED** [review]
Thanks for the update and such thorough documentation @mahoneycm! The alternatives considered section was really helpful.

A few notes on the PR description:
1. Is the alternate approach still relevant? Could you add a brief note as to which you favor and why?
2. Preview links send you to other PR's. 

**Tested**

| Component | Before | After |
| --- | --- | --- |
| Datepicker | [develop](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-date-picker--default&p=all) | [current](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-date-range-remove-mouseover/?path=/story/components-form-inputs-date-picker--default) |
| Date range | [develop](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-date-range-picker--default&p=all) | [current](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-date-range-remove-mouseover/?path=/story/components-form-inputs-date-range-picker--default) |

- [x] No regressions in mouse interactions
- [x] No regressions in keyboard interactions
- [x] Unit tests pass via `npm run test:unit`
- [x] No regressions on 400% zoom

Tested in Chromium 126 & Samsung S23 Android 13 Chrome.

Minor comments below.

File: packages/usa-date-picker/src/index.js (hunk 9 above)
Comment (mahoneycm) [reply packages/usa-date-picker/src/index.js:1796]: This was moved to line 1829. Since we're using `selectedDate` and `rangeDate` I was able to select all three using `getDatePickerContext()`

File: packages/usa-date-picker/src/index.js (hunk 10 above)
Comment (mahoneycm) [reply packages/usa-date-picker/src/index.js:1839]: This is the result of a recent addition to the new ESLint rules that enforce trailing commas for multi-line statements. The comma will get added when running prettier.

This was added in the linter update in #5782

**Comment by mahoneycm** [comment]
@mejiaj I updated the PR description with the appropriate testing links, and additional information on why the alternative solution failed. I also committed one of your suggestions, and replied to the other comments!

Ready for your re-review 👍

**Review by mejiaj — APPROVED** [review]
Thanks for the responses, @mahoneycm!

**Review by amyleadem — APPROVED** [review]
@mahoneycm Looks good to me! The components behave as expected and I no longer experience the error described in the issue. Great work! 

I have tagged @amycole501 and @alex-hull to review so that they can confirm the updated keyboard, zoom, and screen reader behavior in the components meets standards.

**Review by amycole501 — APPROVED** [review]
Tested at standard view and 400% in both JAWS and NVDA. The only minor issue I found was NVDA kept wanting to announce the table ("application table")  which was a little annoying but not a blocker. The mouseover issue seems to have been fixed!

**Review by alex-hull — APPROVED** [review]
Agreed with Amy C. I think it looks good!

**Review by thisisdano — APPROVED** [review]
Great documentation and thorough review. 🎉
