### PR TITLE
USWDS - Tooltip: Make tooltip dismissible with escape key

### LINKED ISSUE #5901: USWDS - Bug: Tooltip needs "escape" key functionality
### Describe the bug

**Dismissible** (tooltip doesn't meet this criteria)
A [mechanism](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#dfn-mechanism) is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an [input error](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#dfn-input-error) or does not obscure or replace other content;
**Hoverable** (tooltip doesn't meet this criteria)
If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;
**Persistent** (tooltip DOES meet this criteria)
The additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.

According to W3C, the tooltip component interaction should be dismissible by hitting the "escape" key. 
https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/
https://www.w3.org/WAI/WCAG22/Techniques/client-side-script/SCR39.html

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/tooltip/
2. keyboard into one of the tooltip button examples
3. hit "escape"
Note how the tooltip remains visible

Additionally, the tooltip does not meet the criteria for "hoverable"
1. Go to https://designsystem.digital.gov/components/tooltip/
2. Hover over the tooltip with a mouse
3. Try to access the tooltip with the mouse. Note that it disappears. According to WCAG it shouldn't.

_If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;_

### Expected Behavior

When you click on the example button and hit 'esc' the tooltip should disappear.

### Screenshots

_No response_

### System setup

PC, Chrome, keyboard

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by amyleadem**
# Summary

**Updated tooltip component behavior to close active tooltips when the `escape` key is pressed.** This allows the component to meet the "dismissible" standard outlined in [WCAG 1.4.13](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html).

> [!Note]
> This issue is slated to be in the same release as #5919, which also edits the tooltip JavaScript. We should confirm there are no conflicts between the two PRs.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5901 

## Related pull requests

[Changelog PR](https://github.com/uswds/uswds-site/pull/2660)

## Preview link

[Tooltip component](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-tooltip-escape/iframe.html?id=components-tooltip--tooltip&viewMode=story)

> [!important]
> In the [default storybook view](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-tooltip-escape/?path=/story/components-tooltip--tooltip), pressing `escape` will not close a tooltip that is triggered by `mouseover` until one of the trigger buttons receives focus. After that, it should work as expected.  However, this issue does not happen when the Story canvas is [opened in its own tab](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-tooltip-escape/iframe.html?id=components-tooltip--tooltip&viewMode=story). For that reason, I do not consider this to be an issue with the component, but rather Storybook. 

## Problem statement

According to W3C, the tooltip component interaction should be dismissible by hitting the "escape" key. 

## Solution

This PR creates the `handleEscape()` function to hide the tooltip when when the `escape` key is pressed. 

## Testing and review
1. Confirm that active tooltips close when you press `escape`. 
1. Confirm no regressions in behavior.
1. Confirm the code meet standards.

### CODE REVIEW

File: packages/usa-tooltip/src/index.js [hunk 1]
```diff
@@ -357,6 +359,24 @@ const setUpAttributes = (tooltipTrigger) => {
   return { tooltipBody, position, tooltipContent, wrapper };
 };
 
+const handleEscape = () => {
+  const activeTooltips = document.querySelectorAll(".is-set");
+  if ( event.keyCode === 27 ) {
```
Comment (anselmbradford) [inline packages/usa-tooltip/src/index.js:364]: Note that `event.keyCode` is deprecated and should be replaced with `event.key === 'Escape'`

File: packages/usa-tooltip/src/index.js [hunk 2]
```diff
@@ -357,6 +357,15 @@ const setUpAttributes = (tooltipTrigger) => {
   return { tooltipBody, position, tooltipContent, wrapper };
 };
```
Comment (amyleadem) [inline packages/usa-tooltip/src/index.js:359]: > [!Note]
> Need to add JSDoc comments here

File: packages/usa-tooltip/src/test/tooltips.spec.js [hunk 3]
```diff
@@ -53,6 +80,22 @@ tests.forEach(({ name, selector: containerSelector }) => {
...
 
+    it("tooltip is visible on mouseover", () => {
+      EVENTS.mouseover(tooltipTrigger);
+      assert.strictEqual(tooltipBody.classList.contains("is-set"), true);
+    });
+
+    it("tooltip is hidden on mouseout", () => {
+      EVENTS.mouseout(tooltipTrigger);
+      assert.strictEqual(tooltipBody.classList.contains("is-set"), false);
+    });
```
Comment (amyleadem) [inline packages/usa-tooltip/src/test/tooltips.spec.js:91]: > [!note]
> Added some missing tests while I was in there

File: packages/usa-tooltip/src/test/tooltips.spec.js [hunk 4]
```diff
@@ -53,6 +80,22 @@ tests.forEach(({ name, selector: containerSelector }) => {
...
+
+    it("tooltip is hidden on escape keydown", () => {
+      tooltipTrigger.focus();
+      EVENTS.escape(body);
```
Comment (amyleadem) [inline packages/usa-tooltip/src/test/tooltips.spec.js:95]: I am struggling to get the escape event to register here. Any ideas?

**Review by mejiaj — COMMENTED** [review]
Added suggestions. Thanks for creating tests.

File: packages/usa-tooltip/src/test/tooltips.spec.js (hunk 4 above)
Comment (mahoneycm) [reply packages/usa-tooltip/src/test/tooltips.spec.js:95]: I've been playing around with this and the issue might have something to do with how we search for `activeTooltips` in the tooltip index.js file.

If I add a console log in lines `376-379`

```js
if (activeTooltips.length === 0) {
  console.log("🟥 no active tooltips");
  return;
}
```
It comes up when running my unit test

```js
  tooltips initialized at document.body
    ✔ trigger is created
    ✔ title attribute on trigger is removed
    ✔ tooltip body is created
    ✔ tooltip is visible on focus
    ✔ tooltip is hidden on blur
    ✔ tooltip is visible on mouseover
    ✔ tooltip is hidden on mouseout
🟥 no active tooltips
    1) tooltip is hidden on escape keydown
    ✔ should not allow for innerHTML of child elements 
```

File: packages/usa-tooltip/src/test/tooltips.spec.js (hunk 3 above)
Comment (amyleadem) [reply packages/usa-tooltip/src/test/tooltips.spec.js]: Update: I moved these tests to #5919 instead since they felt more appropriate there.

File: packages/usa-tooltip/src/index.js [hunk 5]
```diff
@@ -357,6 +359,29 @@ const setUpAttributes = (tooltipTrigger) => {
...
+ */
+
+const handleEscape = (event) => {
+  if (event.key !== "Escape") {
+    return;
+  }
+
+  const activeTooltips = document.querySelectorAll(
+    `.${TOOLTIP_BODY_CLASS}.${VISIBLE_CLASS}`
+  );
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-tooltip/src/index.js]: Good note. I replaced `querySelectorAll` with `selectOrMatches`.

File: packages/usa-tooltip/src/test/tooltips.spec.js (hunk 4 above)
Comment (amyleadem) [reply packages/usa-tooltip/src/test/tooltips.spec.js]: Update: Replaced `body` with `tooltipTrigger` because we know the unit test knows `tooltipTrigger` exists. Also updated the code in `index.js` to check for the `is-set` class instead of `is-visible` to  determine if there are active tooltips since it looked like the `is-visible` class wasn't being added in the test environment.

**Comment by amyleadem** [comment]
@mejiaj @mahoneycm I updated the code based on your recommendations and our offline discussions. This is ready for re-review. Let me know what you think!

**Review by mejiaj — APPROVED** [review]
Looks good. I was able to manually test hover, click, and hitting escape closes the tooltips.

File: packages/usa-tooltip/src/index.js
Comment (mahoneycm) [inline packages/usa-tooltip/src/index.js:1]: ## Storybook focus quirk

I was able to confirm that clicking into the iframe storybook preview also allows the escape functionality to work without needing to tab to a trigger button.

I think this is because the second body element within the iframe isn’t capturing the keyboard interactions until the relative "browser focus" is put inside the iframe

**Review by mahoneycm — APPROVED** [review]
This looks good to me! 

I did want to flag that it looks like the `escape` event listener is active when there are no active tooltips. Adding a `console.log` within the `handleEscape` shows that the function will trigger on escape.

Is that still a requirement for this functionality? I believe we decided it would be better to add the event listener once rather than every time the triggers are hovered but I wanted to make sure since it was listed in the checklist items. 

## Testing checklist

- [x]  Confirm that active tooltips close when you press `escape`.
- [x]  Confirm no regressions in behavior.
- [x]  Confirm the code meet standards.
- [ ]  Confirm the `escape` event listener is only added when the tooltip is active
    - Escape event listener is triggered anytime escape is pressed
- [x]  Tooltip escape functionality works as expected in sandbox

**Comment by amyleadem** [comment]
@amycole501  and @alex-hull  can you confirm that the tooltip now conforms with the "dismissible" criteria in [WCAG 1.4.13](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html)?

**Review by amycole501 — APPROVED** [review]
@amyleadem yes it works great!! I was able to use the esc key to close the tooltip on all examples.

**Review by alex-hull — APPROVED** [review]
Can confirm with Amy C, it should now conform with the dismissible portion of the criteria.

**Review by thisisdano — APPROVED** [review]
Thanks all!
