### PR TITLE
USWDS - File Input: Replace inline javascript to meet content security policy (CSP) standards

### LINKED ISSUE #5990: USWDS - Bug: file upload component is incompatible with a typical content security policy (CSP)
### Describe the bug

The [file input component](https://designsystem.digital.gov/components/file-input/) uses an `onerror` inline Javascript event handler which is incompatible with a typical [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). [This page](https://web.dev/articles/strict-csp#refactor) explains in more detail that inline javascript is not allowed with a nonce- or hash-based approach to strict CSP.

### Steps to reproduce the bug

1. Create a page with a file input component
2. Set a content security policy on the page, e.g. "script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:" (in production the nonce value changes on each request). You can do this by setting the `Content-Security-Policy` HTTP header, or adding an HTML meta element `<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:" />`
3. On your local machine, create an empty text file and rename it to *.jpg
4. Open the page and upload the file to the file input component
5. Observe that the file preview is a broken image and the browser console shows this error: `Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:".

### Expected Behavior

The file preview image is a generic document icon rather than a broken image, and there are no browser security errors.

### Related code

The `onerror` inline event handler is used several times in this section: https://github.com/uswds/uswds/blob/369cf3fdf9abf721a357e864a0f6adbf667ba862/packages/usa-file-input/src/index.js#L394-L427

To meet CSP requirements, these event handlers should be added via addEventListener on the image element rather than the `onerror` attribute.

### Screenshots

**Actual:**
image

**Browser console error:**
image

**Expected:**
image

### System setup

- USWDS version: 3.6.0
- Device: Macbook
- Operating system: Mac OS 14.5
- Browser and version: Chrome 126.0.6478.184 (arm64)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by jeffpw-goog**
# Summary

**Fixed the file input component to meet content security policy standards.** Inline Javascript is forbidden by typical content security policies (CSPs), and this replaces several inline `onerror` handlers in the file input component with addEventListener to avoid that violation.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5990

## Related pull requests

Changelog: https://github.com/uswds/uswds-site/pull/2912

## Preview link

None

## Problem statement

The USWDS library should be compatible with sites that apply a [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) (CSP). Currently the file input component uses `onerror` inline event handlers, which are prohibited by CSP ([source](https://web.dev/articles/strict-csp#refactor)), so the component does not work correctly under a CSP.

## Solution

* Replace `onerror` with calls to `addEventListener`.
* Add a helper method `setPreviewFallback` to remove code duplication
* Update file extension parsing logic to parse the file extension at the end of the filename rather than anywhere in the filename

## Major changes

None

## Testing and review

Steps to test:
1. Run `npm start`
2. Open http://localhost:6006/?path=/story/components-form-inputs-file-input--default
3. Create a text file and upload it to the file input component with the following filenames. In each case confirm that the expected preview icon is shown.
   * file.txt (or any extension not in the list below)
   * file.pdf
   * file.doc
   * file.pages
   * file.xls
   * file.numbers
   * file.mov
   * file.mp4

Steps to test with a CSP policy:

>[!TIP]
>To streamline testing, I copied @jeffpw-goog demo repo work in our sandbox repo so we can utilize the preview build!
>
>[CSP Preview link →](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jeffpw-goog-csp-test/)
>
>You can use this link and complete the steps about without reproducing a CSP policy demo via the steps below.
>
> Leaving the steps below which outline how Jeff made the testing repo
> _Added by @mahoneycm_
>

1. Clone uswds-sandbox
2. Update `src/_includes/head.html`:
   * Add `<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-mynonce' 'strict-dynamic' https:" />`
   * Add `nonce="mynonce"` to the `<link rel="preload" ... as="script">` tag
3. Update `src/_layouts/default.html`:
   * Add `nonce="mynonce"` to the `<script>` tag
   * Add a file input component to the body (I copied from https://designsystem.digital.gov/components/file-input/)
4. Run `npm install "https://github.com/jeffpw-goog/uswds/tree/file-input-csp" --save`
5. Run `npm install && npm init && npm start`
6. Load http://localhost:8080 in your browser
7. Repeat the test cases from above

### CODE REVIEW

File: packages/usa-file-input/src/index.js [hunk 1]
```diff
@@ -393,37 +409,25 @@ const handleChange = (e, fileInputEl, instructions, dropTarget) => {
...
+        case "xls":
+        case "numbers":
+          setPreviewFallback(previewImage, EXCEL_PREVIEW_CLASS);
+          break;
+        case "mov":
+        case "mp4":
+          setPreviewFallback(previewImage, VIDEO_PREVIEW_CLASS);
+          break;
+        default:
+          setPreviewFallback(previewImage, GENERIC_PREVIEW_CLASS);
```
Comment (mahoneycm) [inline packages/usa-file-input/src/index.js:430]: @jeffpw-goog are you still around to help with this issue?

Switch cases aren't common in USWDS code. I was wondering if you'd be open to refactoring back to an `if..else` statement to match USWDS code patterns!

Comment (jeffpw-goog) [reply packages/usa-file-input/src/index.js]: Done

**Comment by jeffpw-goog** [comment]
Sorry @mahoneycm I didn't realize there was a formatting issue in my last push. Fixed now!

**Review by mahoneycm — APPROVED** [review]
Hey there @jeffpw-goog 

Thanks for your continued work here! The PR description and testing steps were great.

This is working like a charm and follows standard USWDS code practices. Flagging others for additional review now!

**Comment by mahoneycm** [comment]
## Testing repo

To streamline testing, I copied @jeffpw-goog demo repo work in our repo so we can utilize the preview build!

[CSP Preview link →](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jeffpw-goog-csp-test/)

You can use this link and complete 1-3 without the second group of instructions to recreate the CSP policy demo.

CC: @mejiaj @amyleadem @cathybaptista

File: packages/usa-file-input/src/index.js [hunk 2]
```diff
@@ -350,6 +350,22 @@ const addPreviewHeading = (fileInputEl, fileNames) => {
...
 };
 
+/** Add an error listener to the image preview to set a fallback image
+ * @param {HTMLImageElement} previewImage - The image element
+ * @param {String} fallbackClass - The CSS class of the fallback image
+ */
+const setPreviewFallback = (previewImage, fallbackClass) => {
+  previewImage.addEventListener(
+    "error",
+    () => {
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:360]: **issue**:  File input event listeners are added in `init()`, can we listen for the error there?

**Review by mejiaj — APPROVED** [review]
Thanks for this contribution. This is a good security fix in general. No issues discovered.

I've tested on the website comparing develop with this branch on uswds/uswds-site#2923.

| Before | After |
| :----- | :---- |
| [live] |     [feature]    |

All variants using different types of files [`pdf, webp, png, tgz`]. Using the file selector and drag and drop.

[live]: https://designsystem.digital.gov/components/file-input/
[feature]: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/test-file-input-uswds-5997/components/file-input/

File: packages/usa-file-input/src/index.js [hunk 3]
```diff
@@ -393,37 +409,17 @@ const handleChange = (e, fileInputEl, instructions, dropTarget) => {
...
-        previewImage.setAttribute(
-          "onerror",
-          `this.onerror=null;this.src="${SPACER_GIF}"; this.classList.add("${VIDEO_PREVIEW_CLASS}")`,
-        );
+      const fileExtension = fileName.split(".").pop();
+      if (fileExtension === "pdf") {
+        setPreviewFallback(previewImage, PDF_PREVIEW_CLASS);
+      } else if (fileExtension === "doc" || fileExtension === "pages") {
+        setPreviewFallback(previewImage, WORD_PREVIEW_CLASS);
+      } else if (fileExtension === "xls" || fileExtension === "numbers") {
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:417]: No longer catches `xslx`.

| Before | After |
| :----- | :---- |
| image | image |


Sample files:
- [XLS 10.xls](https://github.com/user-attachments/files/17560128/XLS.10.xls)
- [test-list.xlsx](https://github.com/user-attachments/files/17560131/test-list.xlsx)

File: packages/usa-file-input/src/index.js [hunk 4]
```diff
@@ -393,37 +409,17 @@ const handleChange = (e, fileInputEl, instructions, dropTarget) => {
...
-        );
-      } else if (fileName.indexOf(".mov") > 0 || fileName.indexOf(".mp4") > 0) {
-        previewImage.setAttribute(
-          "onerror",
-          `this.onerror=null;this.src="${SPACER_GIF}"; this.classList.add("${VIDEO_PREVIEW_CLASS}")`,
-        );
+      const fileExtension = fileName.split(".").pop();
+      if (fileExtension === "pdf") {
+        setPreviewFallback(previewImage, PDF_PREVIEW_CLASS);
+      } else if (fileExtension === "doc" || fileExtension === "pages") {
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:415]: No longer sets icon.

| Before | After |
| :----- | :---- |
| image | image |

Sample file: [notes.docx](https://github.com/user-attachments/files/17560107/notes.docx)

Can't upload `.doc`, but you can create a copy and rename.

**Review by mejiaj — COMMENTED** [review]
Thanks for this contribution. This is a good security fix in general.

I've tested on the website comparing develop with this branch on uswds/uswds-site#2923. I did discover some small differences.

| Before | After |
| :----- | :---- |
| [live] |     [feature]    |

All variants using different types of files. Also used the file selector and drag and drop.

[live]: https://designsystem.digital.gov/components/file-input/
[feature]: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/test-file-input-uswds-5997/components/file-input/

File: packages/usa-file-input/src/index.js (hunk 4 above)
Comment (jeffpw-goog) [reply packages/usa-file-input/src/index.js]: Good catch! Added docx.

File: packages/usa-file-input/src/index.js (hunk 3 above)
Comment (jeffpw-goog) [reply packages/usa-file-input/src/index.js]: Added xlsx.

**Review by mejiaj — APPROVED** [review]
Thanks @jeffpw-goog! Confirming that xlsx and doc icons are appearing.

**Review by thisisdano — APPROVED** [review]
Thank you!
