### PR TITLE
USWDS - Banner: Allow banner to init without accordion requirement

### LINKED ISSUE #5179: USWDS - Bug: Banner has issues with accordion initialization
### Describe the bug

Banner fails to initialize properly because:
1. Component doesn't have its own init method.
2. There's a requirement to USA accordion JS that's not called.

### Steps to reproduce the bug

1. Create a banner component in react
3. Try to initialize based on [react hooks example](https://designsystem.digital.gov/documentation/developers/#:~:text=React%20hooks%20example%3A)
  
  ```js
// UsaBanner.jsx

import { useEffect } from "react";
import banner from "@uswds/uswds/js/usa-banner/";

function UsaBanner() {

  useEffect(() => {
    const ref = document.body;
    // window.uswds
    // initialize
    banner.on(ref);

    return () => {
      banner.off();
    };
  });

…component markup
   ```

### Expected Behavior

Component should initialize in react without requiring uswds-init.

### Screenshots

_No response_

### System setup

- USWDS version: 3.4.0

### Additional context

<details><summary>Outdated notes</summary>
<p></p>

**~Affected components~**
- ~Banner~
- ~Header~
- ~Modal~

~These components currently depend on `usa-js-loading` class from `uswds-init.js`. Users of dynamic frameworks will have unexpected results when trying to initialize.~

~For example, in the case of banner: the banner will appear expanded and won't toggle properly.~

</details> 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mejiaj**
# Summary

**USA Banner now initializes by itself.** Initialize banner with `banner.on()` method. 

It's no longer necessary to import and call `accordion.on()` to initialize banner.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5179.

## Related pull requests

Changelog PR: uswds/uswds-site#2301.

## Preview link

| Current (`develop`) | Feature branch      |
| :------------------ | :------------------ |
| [Accordion Default] | [Accordion Preview] |
| [Banner Default]    | [Banner Preview]    |
| [Test Default]      | [Test Preview]      |

[Accordion Default]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-accordion--default
[Accordion Preview]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jm-feature-banner-init/?path=/story/components-accordion--default
[Banner Default]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-banner--default
[Banner Preview]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jm-feature-banner-init/?path=/story/components-banner--default
[Test Default]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-accordion--test-icons
[Test Preview]: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jm-feature-banner-init/?path=/story/components-accordion--test-icons

All components should work without conflicts.

## Problem statement

Banner didn't have an init method and relied on accordion to toggle content.

## Solution

Banner and accordion JS are separated; with banner being able to initialize and toggle on its own.

## Major changes

Toggle added to banner & accordion ignores banner button - [27181af](https://github.com/uswds/uswds/commit/27181af2e75ef43e5af098fdc08e4f82d899f56f).

## Testing and review

- Visit preview links
- Components should work individually
- Components should work without conflicts in the `Test` variants.

**Additionally**
- Visit [uswds/uswds-sandbox#jm-test-uswds-5179](https://github.com/uswds/uswds-sandbox/tree/jm-test-uswds-5179)
- Run `npm install`
- Visit `http://localhost:8080/accordion-react/`
- Components should initialize alone & work without conflicts

**Checklist**
- [ ] Components should initialize by themselves with import.
- [ ] There should be no regressions in compiled scripts `uswds.js`.

### CODE REVIEW

File: packages/usa-accordion/src/index.js [hunk 1]
```diff
@@ -6,7 +6,8 @@ const { CLICK } = require("../../uswds-core/src/js/events");
 const { prefix: PREFIX } = require("../../uswds-core/src/js/config");
 
 const ACCORDION = `.${PREFIX}-accordion, .${PREFIX}-accordion--bordered`;
-const BUTTON = `.${PREFIX}-accordion__button[aria-controls]`;
+const BANNER_BUTTON = `.${PREFIX}-banner__button`;
+const BUTTON = `.${PREFIX}-accordion__button[aria-controls]:not(${BANNER_BUTTON})`;
```
Comment (mejiaj) [inline packages/usa-accordion/src/index.js:10]: All accordion buttons, except when combined with banner. This helps avoid conflicts because we now initialize banner.

File: packages/usa-banner/src/index.js
Comment (mejiaj) [inline packages/usa-banner/src/index.js:1]: 1. Importing the toggle utility, similar to accordion. 
2. Add an init method to banner.
3. Add functionality to toggle content in `toggleBanner()` line 17-19.

**Review by mahoneycm — APPROVED** [review]
This is working well for me!

- [x] Components working as expected in storybook previews
- [x] Components work without error on `Test` variations 
- [x] React examples work as expected
- [x] Removing `banner.on()` still allows accordion to initialize correctly
- [x] Removing `accordion.on()` still allows banner to initialize correctly

**Review by amyleadem — APPROVED** [review]
This looks good to me! I performed the following tests:
- Opened preview links:
    - [x] Confirmed Storybook components initialized and toggled as expected
    - [x] Removed accordion from `uswds/core/src/js/index.js` and confirmed that banner continues to work as expected
- Opened the [jm-test-uswds-5179](https://github.com/uswds/uswds-sandbox/tree/jm-test-uswds-5179) branch in uswds-sandbox
    - [x] Confirmed the components initialize and work as expected

**Review by thisisdano — APPROVED** [review]
Nice work!
