### PR TITLE
USWDS - In-Page Navigation: Fix scrolling to nested headers

### LINKED ISSUE #5255: USWDS - Bug: In-Page Navigation scrolling does not work with Summary Box
### Describe the bug

When an h2 or h3 tag is used inside of a Summary Box component, it will appear in the In-page navigation component. Clicking on its corresponding link in the navigation does not scroll to its anchor, but rather scrolls to the top of the page. 

### Steps to reproduce the bug

1. Set up a page to use the In-page Navigation component.
2. Add sections of content with h2 and/or h3 tags (the more vertical space this takes up the easier it will be to see the issue).
3. Add a Summary Box component to the page.
4. Make the Summary Box header an h2
5. Click on the link in the In-page Navigation that is supposed to anchor to the Summary Box
6. Instead of scrolling to the Summary Box, the page will scroll to the top of `main`

### Expected Behavior

The In-page Navigation component should scroll to a Summary Box anchor when that Summary Box is part of the nav. 

### Related code

The issue can be seen by visiting [https://designsystem.digital.gov/components/summary-box/](https://designsystem.digital.gov/components/summary-box/) and clicking on 'Key information' under **On this page**.

### Screenshots

_No response_

### System setup

- USWDS version 3.4.1
- Device: Windows PC
- Operating System: Windows 10 Enterprise
- Browser and version: Chrome Version 112.0.5615.138 (Official Build) (64-bit)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by jhancock532**
# Summary

**Fixed issue with in-page navigation being unable to scroll to nested headings.** The in-page navigation can now smooth scroll to headings within the summary box and card components.

> [!important]
> There is currently a build error related to prettier. This should be resolved by PR #6319.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5255

## Related pull requests

_N/A_

## Preview link

[Preview link](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jh-fix-in-page-navigation-scroll-bug/?path=/story/components-in-page-navigation--default)

## Problem statement

The in-page navigation should navigate the user to the section of the page with the indicated heading when the heading link is clicked. 

Currently, clicking on links that refer to nested headings, within the summary box or card components (or any other custom, non-standard USWDS component) causes the page to reset its scroll. 

This poor user experience hinders users from accessing content they are seeking quickly and may mislead users to thinking desired content doesn't exist on the page. Erroneous behaviour reduces users trust in the site and USWDS branded sites as a whole. 

## Solution

The existing code uses the `offsetTop` value of the element to identify how much to scroll down the page. This value is relative to the parent container. To correctly scroll to the location of the element, the `offsetTop` must be added to the `parentOffset` of all the elements parent components. This MR adds a function to calculate the elements true offset in this manner.

An alternative solution would be to refactor the code to use `scrollIntoView` instead. This would involve refactoring the approach we use to test this component, which is being supported using a mocked offsetTop value and watching the `window.scroll` function with `sinon`. 

## Major changes

No major changes to component implementation / testing approach made.

## Testing and review

A new Storybook story in the in-page navigation component has been created for testing. If running storybook locally, go to http://localhost:6006/iframe.html?args=&id=components-in-page-navigation--test-nested-headers&viewMode=story and click on each link in the in-page navigation. The page should correctly scroll to each heading in turn.

Any feedback on the solution would be helpful. I would like to add a test case to cover this fix, but I'm not sure how I'd go about mocking offsetParent only for certain elements. It also feels like if I was to mock this for specific contexts, the test would be verifying a very specific scenario instead of being representative. Using a testing framework such as Playwright instead of Jest would be helpful here.

### CODE REVIEW

**Comment by mahoneycm** [comment]
Hey there @richard8, we have this slated to be a part of our `3.10.0` release. We're currently working on `3.9.0` to be released in the coming weeks and will be able to give this another look after that.

**Review by mejiaj — COMMENTED** [review]
Thanks for this submission, I was able to successfully test all variants in storybook comparing this with develop. Minor comment on const name, otherwise LGTM.

| Before | After |
| :----- | :---- |
| [Develop →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-in-page-navigation--default&p=all) |  [Feature →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jh-fix-in-page-navigation-scroll-bug/?path=/story/components-in-page-navigation--default)  |


### Additional testing

I've also created a testing branch on the website[^1] to verify this fixes the original bug. We'll have to communicate to users of `data-scroll-offset` to double-check the value and make sure there aren't regressions with this change.

### Things I tested

- [x] Unit tests pass
- [x] No regressions in existing variants
- [x] Fixes original bug

[^1]: uswds/uswds-site#2978

File: packages/usa-in-page-navigation/src/index.js [hunk 1]
```diff
@@ -187,20 +187,29 @@ const getSectionId = (value) => {
...
   const inPageNavEl = document.querySelector(`.${IN_PAGE_NAV_CLASS}`);
   const inPageNavScrollOffset =
     inPageNavEl.dataset.scrollOffset || IN_PAGE_NAV_SCROLL_OFFSET;
 
+  const offsetTop = getTotalElementOffset(el);
+
   window.scroll({
     behavior: "smooth",
-    top: el.offsetTop - inPageNavScrollOffset,
-    block: "start",
```
Comment (mejiaj) [inline packages/usa-in-page-navigation/src/index.js:203]: > [!NOTE]
> Removing `block` had no effect. Not seeing it as an option in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) either.

File: packages/usa-in-page-navigation/src/index.js [hunk 2]
```diff
@@ -187,20 +187,29 @@ const getSectionId = (value) => {
...
 };
 
+/**
+ * Recursively calculate a heading element's offset from the top of the page.
+ *
+ * @param {HTMLElement} el A heading element
+ */
+const getTotalElementOffset = (el) =>
+  el.offsetTop + (el.offsetParent && getTotalElementOffset(el.offsetParent));
+
```
Comment (mahoneycm) [inline packages/usa-in-page-navigation/src/index.js:197]: **question:** Is the el.offsetParent && a truthy check to check for parent offset? If so, we might want to make the check a bit more human-readable to match existing USWDS patterns.

**suggestion:** Opt for `if` statement:

```suggestion
const getTotalElementOffset = (el) => {
  if (el.offsetParent) {
    return el.offsetTop +  getTotalElementOffset(el.offsetParent);
  } 

  return el.offsetTop
}
```

Curious if the rest of the team has another preference!

File: packages/usa-in-page-navigation/src/index.js [hunk 3]
```diff
@@ -187,20 +187,29 @@ const getSectionId = (value) => {
...
 /**
  * Scroll smoothly to a section based on the passed in element
  *
- * @param {HTMLElement} - Id value with the number sign removed
+ * @param {HTMLElement} el A heading element
```
Comment (mahoneycm) [inline packages/usa-in-page-navigation/src/index.js:201]: **polish:** It looks like the `el` here is actually the anchor element if we want to specify

```suggestion
 * @param {HTMLAnchorElement} el - The link to the section heading.
```

File: packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Comment (mahoneycm) [inline packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: **Praise:** Thank you for creating this test story and following our naming conventions! This made it much easier to test.

Comment (mahoneycm) [reply packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: **question:** Would you have the bandwidth to create a unit test for this work as well? If not, let us know so we can coordinate making one! Thanks!

File: packages/usa-in-page-navigation/src/index.js
Comment (mahoneycm) [inline packages/usa-in-page-navigation/src/index.js:1]: > [!IMPORTANT]
> We'll need to update the header offset logic on our website to account for this change.
>
> Installing this branch on Site did resolve the bug where nested headers would cause the window to scroll to the top of the page but due to our custom JS the offset was not calculated correctly.

**Review by mahoneycm — CHANGES_REQUESTED** [review]
This is looking great @jhancock532! Thank you so much for your contribution.

I left a couple questions and possible suggestions if you have the bandwidth. Excited to get this merged 👍

File: packages/usa-in-page-navigation/src/index.js
Comment (mejiaj) [reply packages/usa-in-page-navigation/src/index.js:1]: Good point. Noted in https://github.com/uswds/uswds-site/pull/2978#discussion_r1850942384.

File: packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Comment (jhancock532) [reply packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: Hello, thank you for the review. I'll be able to look into this and make fixes from the 10th of December, when our new sprint of work starts (hopefully that's not too much of a delay). 

I can try my best at creating a unit test to cover this behavior, if you have any suggestions on how to approach this it would be much appreciated. I left a comment at the bottom of the MR description wondering how we'd handle mocking the `offsetParent` value when using Jest - there might be another way of handling this that I've not thought of, or a more creative solution to test the same behavior.

Comment (jhancock532) [reply packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: Unfortunately other work has come up and this has been pushed back until some point in the new year, I can leave another comment when I find out more - if this is a risk of being a blocker then others can make changes to this MR as well

Comment (mahoneycm) [reply packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: Thank you for the heads up! I moved the issue to `in progress` and added the `triage` label so that this stays on our radar. If we take over next steps, we'll let you know.

I appreciate the contributed work and communication!

**Comment by mgwalker** [comment]
I believe this also fixes #6295.

File: packages/usa-in-page-navigation/src/index.js [hunk 4]
```diff
@@ -187,20 +187,29 @@ const getSectionId = (value) => {
...
  */
 const handleScrollToSection = (el) => {
   const inPageNavEl = document.querySelector(`.${IN_PAGE_NAV_CLASS}`);
   const inPageNavScrollOffset =
     inPageNavEl.dataset.scrollOffset || IN_PAGE_NAV_SCROLL_OFFSET;
 
+  const offsetTop = getTotalElementOffset(el);
```
[the remark this answers is not in the document]
Comment (mejiaj) [reply packages/usa-in-page-navigation/src/index.js:218]: Fixed in 3be1ceac7.

File: packages/usa-in-page-navigation/src/index.js (hunk 3 above)
Comment (mejiaj) [reply packages/usa-in-page-navigation/src/index.js:211]: Fixed in 3be1ceac7.

File: packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Comment (mahoneycm) [reply packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig:1]: Hey there @jhancock532! 

I took a stab at creating the unit test. It pointed out some shortcomings in our current unit test for in-page nav. For the time being, I don't think this needs to be a blocker for the work.

Thank you for your contribution! I'm going to approve and hope we can improve our testing as a future enhancement.

**Review by mahoneycm — DISMISSED** [review]
Feature is working great! Great enhancement to the in-page navigation.

**Limitations of unit testing**

Since `jsdom` doesn't emulate positions, our unit tests are limited to feining offset based on how many elements are on the page. We should look into improving these tests in the future but I don't believe it should be a blocker for this work 👍

**Review by mejiaj — DISMISSED** [review]
Thanks for contributing!

There is some awkwardness when clicking on headers in our test pages because of the lack of content. Especially when clicking on nested headings, but this behavior can also be seen on [develop](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-in-page-navigation--default&p=all).

### Follow-up changes

1. **Mark as potentially breaking.** We should also make this as a `potentially breaking change` and suggest to users to revisit their implementation if they've modified `data-scroll-offset` (like we did in site). 
2. **Update implementation on site.** We should follow instructions [here](https://github.com/uswds/uswds-site/pull/2978#discussion_r1850942384) to update the implementation on site.
3. **Explore ways to improve our testing.** Our tests could include more content and our unit tests could use a spike to explore ways to more reliably test this component.

**Comment by mahoneycm** [comment]
@jhancock532 , thank you for this contribution!

For security reasons, USWDS requires that all commits to this repo have a verified signature. Your commits are registering as unverified, so we will need you to complete the following steps before this contribution can be merged:
1. **Set up signature verification in GitHub.** Use one of the following GitHub guides to set up your verification signature:
    - [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) 
    - [SSH commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification)
1. **Rebase your commits with your verified signature.** Once your signature is set up, complete the following steps in the terminal to update the verification status of your previous commits:

    ```
    git checkout branch-name
    git rebase origin/develop
    git push --force-with-lease
    ```

Please let us know if you have any questions.

**Comment by jhancock532** [comment]
Hello @mahoneycm, I'm having some difficulty rebasing with signed commits, I might be going about it the wrong way. 

Following the above instructions locally, there are then 1809 rebase steps, and the `package-lock.json` file is flagging as a conflict to be resolved from step 5 onwards (this file appears to cause a rebase conflict every few steps or so, I'm not sure why though - something to do with merging in develop?). 

Does it make sense for me to create a new MR with verified commits for the changes, as this MR has been flagged for more code review anyway? The failing pipeline seems to be an unrelated issue with the date-picker component which shouldn't be affected by this MR.

**Comment by mahoneycm** [comment]
@jhancock532 thanks for reaching out! I'm going to see if I can rebase this for you with verified commits. If all goes well, we should be able to avoid you having to create a new PR 👍

**Review by heymatthenry — APPROVED** [review]
Woohoo! Thanks, @jhancock532 and team!
