### PR TITLE
USWDS - File input: Fix issues with voice command

### LINKED ISSUE #5192: USWDS - Bug: File input issues with voice command and screen readers
## Describe the bug

Testing revealed issues when using the file input component with various assistive technologies.

Thanks to @briandeconinck for flagging this in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1499#issuecomment-1458661931.

More details about the issues can be found in this [Google doc](https://docs.google.com/document/d/1kqN166hHXDSkmsdHXL5dtD8u0nkHD5oJzVuptiY0Yhw/edit#) :lock:

### Screen readers:
The input `aria-label` provides insufficient information for interaction. This default `aria-label` does not clearly communicate what the input is or what the user should do, which can lead to confusion. 

###  Voice command: 
Voice command does not work in an intuitive way. A user would expect to say something like "Click drag file here or choose from folder" or "Click choose from folder" to interact with the file input because that is the text that is visible in the component. 

Instead, the only ways to interact with the component through voice are to either:
- Give a command using the text found in the `aria-label`  
- Work with the mouse grid or other cumbersome mouse-based voice commands.

Both of these solutions would be very frustrating for a VC user. 

## Steps to reproduce the bug

Using Voice command software Dragon NaturallySpeaking, attempt to open the file input component with voice command. 

Intuitive methods:
- Reading the visible component text - does not work:
    - “Click choose from folder” is not recognized.
    - "Click drag file here or choose from folder" is not recognized.

Alternative methods:
- Reading the aria-label - works: 
    - Voice command “Click no file selected” opens the file selection window.
    - Voice command “Click cancel”; closes the file selection window.
    - However, the `aria-label` is not visible and a user would not intuitively find this.
- Identifying all links - does not work:
    - “Click link” will highlight all links and assign each a number, but this does not recognize file input 
- Using mouse grid or other mouse commands - works, but is a frustrating experience:
    - “Open mouse grid” should open a grid but during the demo it proved to be frustrating. 
    - “Move mouse up” will move the mouse until you tell it to stop; this is a method of last resort. 

> Demonstration with Dragon:

 > https://user-images.githubusercontent.com/6844775/223518739-84b4b68e-3312-4669-a8b5-d58a3f0f60e6.mp4

> _Originally posted by @briandeconinck in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1499#issuecomment-1458661931_

## Expected Behavior

1. Voice control users should be able to give commands using the visible text to move focus to and interact with the input.
    - The voice command “Click, [visible text]” should move focus into an input and allow the user to add content. 
        - For example, in the current file input example, users would expect to say "Click drag file here or choose from folder" or “Click choose from folder” to interact with the component.
1. Screen reader users should be given clear and explicit labels and instructions. 
    - Labels should give information about the role of a given input and should give users instructions about what action they must take to interact with the input.

## Additional context
- We should confirm that `aria-label` takes precedence over `label in our available screen readers.

### PR DESCRIPTION
**Pull request by amyleadem**
# Summary
**Improved the file input experience for voice command and screen reader users.** Voice command users can now more easily interact with the component by speaking the visible instructions text. Additionally, screen reader users now have access to both the visible instructions text (in the `aria-label`) and the file selection status (in a newly created screen reader-only element).

## Breaking change

This is not a breaking change.
All changes have been handled dynamically.

## Related issue

Closes #5192 

As a future enhancement, issue #5238 will create data attributes that will allow users to customize the status and instructions text. 

## Related pull requests

Changelog update: https://github.com/uswds/uswds-site/pull/2088

## Preview link

Preview link: [File input](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-file-input-vc/?path=/story/components-form-inputs-file-input--default)

## Problem statement
Users of assistive technologies should be able to intuitively access all form elements, understand what action they should take, and receive feedback so that they can confirm that the information they have added is correct. However, the file input component presents problems for both screen reader and voice command users:

###  Voice command issues 
Because of file input's structure, voice command does not work in an intuitive way. A user would expect to vocalize the text shown on screen as part of a  "Click" command. For file input, this would mean the user would expect to say something like "Click drag file here or choose from folder" or ""Click choose from folder" to interact with the file input. However, neither of these work because the accessibility tree does not include this information. 

### Screen readers issues
Screen reader users do not have access to the instructions text ("Drag file here or choose from folder"). Instead, the `aria-label` provides feedback on the file selection status. This is insufficient information for interaction. The default `aria-label` "no file selected"  does not clearly communicate what the input is or what the user should do, which can lead to confusion. 

## Solution
To allow voice command users to easily access the file input component, we should make sure the input `aria-label` matches the visible text as the status changes.

To allow screen reader users to continue to confirm their file selection, we should move the file status from the `aria-label` to a dynamically created `sr-only` element.

## Major changes
1. Moved the file status update from the input aria-label to a new sr-only element.
2. The input aria-label now matches the visible instruction text so that voice command users can access the component with intuitive commands
3. Broke out `buildFileInput()` into separate functions:  `createTargetArea` and `createVisibleInstructions` 
4. Standardized and added clarity to JSDoc comments

## Possible future enhancements
Converting the CTA text ("choose from folder", "change file") from a `<span>` element to a `<button>` element might improve consistency in Voice Command software. It could also give an alternative method for voice control users so that they can highlight all interactive elements on the page and select the element they want to click. 

### Accessibility:
- Confirm that the screen reader experience is intuitive and makes sense
- Confirm that you can open the file input dialog via voice command (If available. It would be helpful to know which tools you used)
- When file status changes, confirm that the status update is read on a screen reader

### Developers:
The following items should be confirmed: 
- Confirm that the aria-label on the input matches the visible instruction text:
    - Default text = “Drag file here or choose from folder”
    - One file selected = “Change file”
    - More than one file selected = “Change files”
    - File removed = “Drag file here or choose from folder”
- Confirm that the status element (.usa-sr-only) updates correctly when:
    - One file selected = "You have selected the file: [fileName]"
    - More than one file selected  = "You have selected [x] files: [fileName], [fileName], etc"
    - File removed = "No file selected."
- In the [multiple inputs test page](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-file-input-vc/iframe.html?args=&id=components-form-inputs-file-input--test-multiple-inputs&viewMode=story), confirm that each input creates unique status update.
- Confirm no visual regressions
- Confirm no behavioral regressions
- Confirm the JavaScript is well-structured and makes sense
- [ADDITION] Confirm that status element is not created for disabled or aria-disabled file inputs

### CODE REVIEW

**Comment by briandeconinck** [comment]
Hi Amy! Sorry for the slow reply.

I see the updated `aria-label` and I believe it should work... but when I actually test it, it's hit-or-miss. Digging through some 7+ year old forum threads and it sounds like there's some inconsistency with how Dragon plays with file inputs. But the `aria-label` is giving me a match at least some of the time, with both the full text and just the "choose from folder" substring. Accounting for odd behavior with Dragon, that might be good enough. 🤷 

I will note that since the instruction text has the fake-link styling, the command "Click link" still doesn't highlight the input as an option, which would typically be the next thing I try if "Click choose from folder" doesn't get a match. Maybe make it an actual link or button with a JS action to map it to the input? I believe even if it's removed from the tab order with `tabindex="-1"` it should still work with Dragon, but I haven't tested that.

Up to you whether you want to pursue that. What you have here is definitely an improvement and should work most of the time for Dragon users (again, accounting for possible Dragon weirdness).

**Comment by amyleadem** [comment]
Thanks for the response, @briandeconinck! Your test results are helpful. Since we aren't hitting consistent results with `aria-label` in Dragon and other voice command methods, I am going to explore if there are alternate paths here. Thanks for the suggestions and I appreciate you taking the time! I'll tag you again if there are any updates.

**Review by mahoneycm — APPROVED** [review]
Thanks for taking this on Amy! The screen reader functionality is working like a charm

- [x] Confirmed no visual or behavioral regression for file input
- [x] Confirmed aria-label changes to fit the current instructions via:
    - [x] No file selected
    - [x] Single file selected
    - [x] Multiple files selected
    - [x] File removed
- [x] Confirmed the status element updates and reads out correctly
   - [x] Single file
   - [x] Multiple files
   - [x] No files
- [x] Confirmed the dynamic changes occur correctly when multiple inputs exist on the same page 
- [x] Reviewed JS and did not find any examples of how we should restructure 

Overall I think this is a great example of a feature improvement that only changes the code for the better! I will definitely revisit how you structured this when making adjustments to components in the future 💯

File: packages/usa-file-input/src/index.js [hunk 1]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+  defaultStatus = `No ${item} selected.`;
+  statusEl.setAttribute("data-default-status-text", defaultStatus);
+  statusEl.textContent = defaultStatus;
+
+  // Add initial instructions for input usage
+  dragText = `Drag ${item} here or`;
+  chooseText = "choose from folder";
+  defaultInstructionsText = `${dragText} ${chooseText}`;
+  fileInputEl.setAttribute("aria-label", defaultInstructionsText);
+  fileInputEl.setAttribute("data-default-aria-label", defaultInstructionsText);
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:156]: Is this just to store the original value? We could avoid modifying markup by saving it in JS at the start of the function.

```suggestion
  const defaultAriaLabel = fileInputEl.getAttribute("aria-label"); // defaultInstructionsText
```

File: packages/usa-file-input/src/index.js [hunk 2]
```diff
@@ -210,11 +241,70 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
     Array.prototype.forEach.call(filePreviews, removeImages);
   }
 };
 
+/**
+ * Update the screen reader-only status message after interaction
+ * @param {HTMLElement} statusElement - screen-reader only container for file status updates
+ * @param {HTMLElement} fileNames - uploaded files
+ * @param {HTMLElement} fileStore - array of uploaded file names
+ */
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:253]: Let's do something similar to the comment above:

1. Use full sentences.
1. Add a space after description.
1. Try to use more accurate element descriptors instead of generic HTMLElement (if possible)

File: packages/usa-file-input/src/index.js [hunk 3]
```diff
@@ -210,11 +241,70 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
+    statusEl.textContent = statusMessage;
+  }, 1000);
+};
+
+/**
+ * Hide the initial instructions and show the preview heading
+ * @param {HTMLElement} fileInputEl - file input element
+ * @param {HTMLElement} fileNames - uploaded files
+ * @param {HTMLElement} dropTarget - target area div that encases the input
+ * @param {HTMLElement} instructions - text to inform users to drag or select files
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:279]: Comment-style, same as above.

File: packages/usa-file-input/src/index.js [hunk 4]
```diff
@@ -210,11 +241,70 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
+ */
+const addPreviewHeading = (
+  fileInputEl,
+  fileNames,
+  dropTarget,
+  instructions
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:285]: Are all these params needed?

File: packages/usa-file-input/src/index.js [hunk 5]
```diff
@@ -313,24 +389,18 @@ const handleChange = (e, fileInputEl, instructions, dropTarget) => {
...
+    // Reset input aria-label with default message
+    fileInputEl.setAttribute("aria-label", defaultAriaLabelText);
+  }
 
-    // Hides null state content and sets preview heading class
-    if (filePreviewsHeading) {
-      instructions.classList.add(HIDDEN_CLASS);
-      filePreviewsHeading.classList.add(PREVIEW_HEADING_CLASS);
-    }
+  if (fileNames.length > 0) {
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:399]:
```suggestion
  if (fileNames.length === 0) {
    // Reset input aria-label with default message
    fileInputEl.setAttribute("aria-label", defaultAriaLabelText);
  } else {
```

**Review by mejiaj — CHANGES_REQUESTED** [review]
Nice job! I was able to test in VoiceOver and got the correct description & instructions. Added some comments to try to improve clarity and simplify some of the functions.

**Comment by amycole501** [comment]
I was able to successfully and very easily get windows speech recognition to activate the file upload link. Sharky wasn't able to do it but I think that's a limitation of JAWS and not the coding. I was easily able to get the keyboard tabbing to work as well.

**Review by amycole501 — APPROVED** [review]
Worked great using Windows speech recognition. Sharky didn't work but that's a limitation of JAWS and not so much the coding.

File: packages/usa-file-input/src/index.js (hunk 5 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Nice cleanup. Updated in: [aaecb66](https://github.com/uswds/uswds/pull/5213/commits/aaecb668aff54e4c8c88ad60c28205890846eb4f)

File: packages/usa-file-input/src/index.js [hunk 6]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+  fileInputEl,
+  fileInputParent,
+  instructions,
+  dropTarget
+) => {
+  const statusEl = document.createElement("div");
+  const acceptsMultiple = fileInputEl.hasAttribute("multiple");
+  const instructionsEl = instructions;
+  const items = "files";
+  let item = "file";
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Nice improvement. Updated in https://github.com/uswds/uswds/pull/5213/commits/08cb947c44d3895b812238a5c987f74f58b3a9ba

File: packages/usa-file-input/src/index.js [hunk 7]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+const buildStatusMessage = (
+  fileInputEl,
+  fileInputParent,
+  instructions,
+  dropTarget
+) => {
+  const statusEl = document.createElement("div");
+  const acceptsMultiple = fileInputEl.hasAttribute("multiple");
+  const instructionsEl = instructions;
+  const items = "files";
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Updated to `itemsLabel` in https://github.com/uswds/uswds/pull/5213/commits/bb8cc28681c12d26ca14e26798a0664c2340a508

File: packages/usa-file-input/src/index.js [hunk 8]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+  statusEl.setAttribute("aria-live", "polite");
+  fileInputParent.insertBefore(statusEl, dropTarget);
+
+  // If multiple attribute enabled, use the plural
+  if (acceptsMultiple) {
+    item = items;
+  }
+
+  // Add initial file status message
+  defaultStatus = `No ${item} selected.`;
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Appreciate the improvement! Updated the definitions with defaults in [5c3a80c](https://github.com/uswds/uswds/pull/5213/commits/5c3a80cd62e53a2c51a908fb5ced3b6944fcb0d8)

File: packages/usa-file-input/src/index.js [hunk 9]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+  statusEl.setAttribute("data-default-status-text", defaultStatus);
+  statusEl.textContent = defaultStatus;
+
+  // Add initial instructions for input usage
+  dragText = `Drag ${item} here or`;
+  chooseText = "choose from folder";
+  defaultInstructionsText = `${dragText} ${chooseText}`;
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Appreciate the improvement! Updated the definitions with defaults in [5c3a80c](https://github.com/uswds/uswds/pull/5213/commits/5c3a80cd62e53a2c51a908fb5ced3b6944fcb0d8)

File: packages/usa-file-input/src/index.js [hunk 10]
```diff
@@ -110,55 +111,67 @@ const createUniqueID = (name) =>
...
- * Builds full file input component
- * @param {HTMLElement} fileInputEl - original file input on page
- * @returns {HTMLElement|HTMLElement} - Instructions, target area div
+ * Scaffold the file input component with a parent wrapper and
+ * Create a target area overlay for drag and drop functionality
+ *
+ * @param {HTMLInputElement} fileInputEl - The input element.
+ * @returns {HTMLDivElement} The drag and drop target area.
  */
-const buildFileInput = (fileInputEl) => {
```
Comment (amyleadem) [inline packages/usa-file-input/src/index.js:117]: > **Note**
> Broke buildFileInput into multiple functions --> 
> - `createTargetArea` - creates the component's parent wrapper and target area 
> - `createVisibleInstructions` - creates the initial drag/choose instructions. Also sets the input's `aria-label` with default interaction instructions (The input's aria-label previously received the file status updates)
> - `createSROnlyStatus` - Creates an sr-only element that receives with file status updates

File: packages/usa-file-input/src/index.js [hunk 11]
```diff
@@ -210,52 +263,102 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
  * @param {event} e
- * @param {HTMLElement} fileInputEl - file input element
- * @param {HTMLElement} instructions - text to inform users to drag or select files
- * @param {HTMLElement} dropTarget - target area div that encases the input
+ * @param {HTMLInputElement} fileInputEl - The input element.
+ * @param {HTMLDivElement} instructions - The container for visible interaction instructions.
+ * @param {HTMLDivElement} dropTarget - The drag and drop target area.
  */
 
 const handleChange = (e, fileInputEl, instructions, dropTarget) => {
```
Comment (amyleadem) [inline packages/usa-file-input/src/index.js:344]: > **Note**
> Created `addPreviewHeading` function to separate out preview heading tasks from `handleChange`
> This was done to add clarity and improve readability.

File: packages/usa-file-input/src/index.js [hunk 12]
```diff
@@ -109,19 +110,64 @@ const makeSafeForID = (name) => name.replace(/[^a-z0-9]/g, replaceName);
...
+ * @param {HTMLElement} fileInputEl - original file input on page
+ * @param {HTMLElement} fileInputParent - file input wrapper with the DROPZONE_CLASS
+ * @param {HTMLElement} instructions - text to inform users to drag or select files
+ * @param {HTMLElement} dropTarget - target area div that encases the input
+ */
+const buildStatusMessage = (
+  fileInputEl,
+  fileInputParent,
+  instructions,
+  dropTarget
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Simplified params and broke this (and `buildFileInput()`) into separate functions: `createTargetArea`, `createSROnlyStatus`, `createVisibleInstructions` 
in commit [953b886](https://github.com/uswds/uswds/pull/5213/commits/953b886ded202c4129880cd989f8fc6eebd39b8e)

More details on the updated functions can be found in [this comment](https://github.com/uswds/uswds/pull/5213#discussion_r1190365153).

File: packages/usa-file-input/src/index.js (hunk 3 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Updated comments in [7174273](https://github.com/uswds/uswds/pull/5213/commits/7174273d322cb75c142fcaa496d871d4dd971562). Let me know if you see any opportunity for improvement.

File: packages/usa-file-input/src/index.js (hunk 2 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Updated comments in [7174273](https://github.com/uswds/uswds/pull/5213/commits/7174273d322cb75c142fcaa496d871d4dd971562). Let me know if you see any opportunity for improvement.

Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Updated comments in [7174273](https://github.com/uswds/uswds/pull/5213/commits/7174273d322cb75c142fcaa496d871d4dd971562). Let me know if you see any opportunity for improvement.

File: packages/usa-file-input/src/index.js (hunk 4 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Simplied params in [866d335](https://github.com/uswds/uswds/pull/5213/commits/866d335ef99f0a712551bb31e44901211006f6c6)

File: packages/usa-file-input/src/index.js (hunk 1 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: I wasn't sure how to pull this across functions, into `handleChange()`. Might be just a brain hiccup. Maybe we can get on a call tomorrow?

**Comment by amyleadem** [comment]
@mejiaj Thanks for the suggestions! I have made the requested updates. FYI - I've restructured and renamed the `buildFileStatus` and `buildStatusMessage` functions to improve clarity and readability.  Details can be found in [this comment](https://github.com/uswds/uswds/pull/5213#discussion_r1190365153).

Let me know if you have any questions.

**Comment by amyleadem** [comment]
Note: sending this back to draft to improve the experience for screen reader experience for disabled component.

**Comment by amyleadem** [comment]
I added a check for the `disabled` attribute before generating the sr-only status message. Let me know if you see any issues with this!

**Review by mejiaj — CHANGES_REQUESTED** [review]
Focused on code in this review and added some comments. Overall no issues, but some minor areas we can improve.

Mainly, saving the default aria label in code and possible duplicate check on disabled state.

File: packages/usa-file-input/src/index.js
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js:1]: Opened issue https://github.com/uswds/uswds/issues/5299 to address this.

File: packages/usa-file-input/src/index.js [hunk 13]
```diff
@@ -226,32 +295,89 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
+
+  if (fileNames.length === 1) {
+    previewHeadingText = Sanitizer.escapeHTML`Selected file <span class="usa-file-input__choose">${changeItemText}</span>`;
+  } else if (fileNames.length > 1) {
+    changeItemText = "Change files";
+    previewHeadingText = Sanitizer.escapeHTML`${fileNames.length} files selected <span class="usa-file-input__choose">${changeItemText}</span>`;
+  }
+
+  // Hides null state content and sets preview heading
+  instructions.classList.add(HIDDEN_CLASS);
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Replaced `HIDDEN_CLASS` in favor of the `hidden` attribute in [4278f23](https://github.com/uswds/uswds/pull/5213/commits/4278f2323a83d5404f36125a5a7a1f4cd717d8fb)

File: packages/usa-file-input/src/index.js [hunk 14]
```diff
@@ -120,37 +121,45 @@ const createUniqueID = (name) =>
...
- * @param {HTMLElement} fileInputEl - original file input on page
- * @returns {HTMLElement|HTMLElement} - Instructions, target area div
+ * Determines if the singular or plural item label should be used
+ * Determination is based on the presence of the `multiple` attribute
+ *
+ * @param {HTMLInputElement} fileInputEl - The input element.
+ * @returns {HTMLDivElement} The singular or plural version of "item"
  */
-const buildFileInput = (fileInputEl) => {
+const setItemsLabel = (fileInputEl) => {
```
[the remark this answers is not in the document]
Comment (amyleadem) [reply packages/usa-file-input/src/index.js]: Good catch. Updated in [38cf451](https://github.com/uswds/uswds/pull/5213/commits/38cf4512e0dbb130d8f2df0f0e1d3c55b0456a76)

**Review by amyleadem — COMMENTED** [review]
@mejiaj Thanks for the helpful review! I have addressed all comments. Please let me know if you have questions.

File: packages/usa-file-input/src/index.js [hunk 15]
```diff
@@ -120,37 +121,45 @@ const createUniqueID = (name) =>
...
-  let defaultAriaLabel;
 
   // Adds class names and other attributes
   fileInputEl.classList.remove(DROPZONE_CLASS);
   fileInputEl.classList.add(INPUT_CLASS);
   fileInputParent.classList.add(DROPZONE_CLASS);
   box.classList.add(BOX_CLASS);
-  instructions.classList.add(INSTRUCTIONS_CLASS);
-  instructions.setAttribute("aria-hidden", "true");
   dropTarget.classList.add(TARGET_CLASS);
```
[the remark this answers is not in the document]
Comment (mejiaj) [reply packages/usa-file-input/src/index.js:155]: Gotcha, thanks for that explanation. My main concern was lack of clarity when it came time to adding all the DOM elements and seeing what went where.

**Comment by amyleadem** [comment]
@mejiaj I confirmed that your update adds the disabled class as expected when either `disabled` or `aria-disabled` is present on the input element. Thanks for cleaning up the disabled behavior so that the attributes aren't touched on init. Appreciate it! 

Will you let me know if you see anything else?

File: packages/usa-file-input/src/index.js [hunk 16]
```diff
@@ -224,34 +287,89 @@ const removeOldPreviews = (dropTarget, instructions, inputAriaLabel) => {
...
+};
+
+/**
+ * Show the preview heading, hide the initial instructions and
+ * Update the aria-label with new instructions text
+ *
+ * @param {HTMLInputElement} fileInputEl - The input element.
+ * @param {Object} fileNames - The selected files found in the fileList object.
+ */
+const addPreviewHeading = (fileInputEl, fileNames) => {
```
Comment (mejiaj) [inline packages/usa-file-input/src/index.js:329]: This function adds text describing:
- How many files
- Which files have been uploaded

So far I've only gotten it to read after initial upload. If I move to another area and comeback it doesn't get read on VoiceOver Chromium 113.

### Possible Future enhancements:
1. Add a unique ID to this message and tie it to the component via `aria-labelledby` [[MDN on aria-labelledby]](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby)
2. Move the preview heading text so it always gets read.
3. Dynamically update the aria-label
    
**Move the preview heading text example**

https://github.com/uswds/uswds/assets/3385219/e9cebeef-9ba5-4eab-9f68-5c83293f61e6

**Review by mejiaj — APPROVED** [review]
Code looks good, I just have a comment on `addPreviewHeading()`. This function adds a description for screen readers for how many files and their names.

On voiceover this only gets read once after upload. We could improve this by having it be read on focus as a fast follow-up.

File: packages/usa-file-input/src/index.js (hunk 16 above)
Comment (amyleadem) [reply packages/usa-file-input/src/index.js:329]: Thanks @mejiaj. I've opened https://github.com/uswds/uswds/issues/5304 to start looking into this. I will begin investigating as a fast follow-up.

**Review by thisisdano — APPROVED** [review]
Nice work
