### PR TITLE
USWDS - Navigation: Close actions.

### LINKED ISSUE #3396: Menu dropdown should close on `Esc`.
## Description

Based on discussion in slack thread:
https://gsa-tts.slack.com/archives/C3F14AHSQ/p1587058923090100

`Esc` key should be able to close the main menu and reset its subnavs.

Involves:
- [x] Updating `navigation.js`
- [x] Updating unit tests

## Steps to reproduce the issue

1. Visit [extended megamenu w/ dropdowns](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.6.0/components/preview/header--extended-mega.html)
2. Expand menu item
3. Hit `esc`, menu doesn't close

### LINKED ISSUE #3528: Active navigation does not close when focus moves outside
## Description

With collapsible navigation menu items, the contents can be shown by activating the menu accordion, at which point the user can <kbd>Tab</kbd> through the navigation options. Once the user has tabbed through all of the available options and proceeds to the next tabbable element on the page, the menu remains open. This may be unexpected, and is at least inconsistent with existing behavior to dismiss the active navigation menu when _clicking_ on the page body.

## Steps to reproduce the issue

1. Navigate to [Basic Header demo](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.7.1/components/preview/header--basic.html)
2. <kbd>Tab</kbd> through page contents to "Current section" collapsible menu
3. Press <kbd>Space</kbd> to expand menu items
4. Press <kbd>Tab</kbd> tab to proceed through menu items, until options are exhausted and then focus moves to the next "Section" navigation menu

**Expected behavior:** The "Current section" expanded menu should be closed.
**Actual behavior:** The "Current section" expanded menu remains open.

## Additional information

There could be a counter-argument here that focus transitions should not be used to signal a change in the expanded state of the menu. There is conflicting advice on this point.

>As pictured, whether that menu is open or closed should be communicated with `aria-expanded`. You should only change this state on click, not on focus. Users do not usually expect an explicit change of state on a mere focus event.

https://inclusive-components.design/menus-menu-buttons/

>In this case, the submenu is opened by a script when the user activates the top-level item and closed when the focus leaves the submenu.

https://www.w3.org/WAI/tutorials/menus/flyout/#use-parent-as-toggle

In any case, there already appears to be some handling of this in dismissing the active menu when _clicking_ somewhere on the page, seemingly intending to capture a similar sort of focusout behavior.

Possible remediation options:

- Remove click-to-dismiss behavior
- Update behavior of menu to dismiss active menu when focus leaves

Relevant code: https://github.com/uswds/uswds/blob/develop/src/js/components/navigation.js

I began some initial exploration of a possible fix. It's worth noting that the use of an event delegation library makes this more difficult in how ideally this would be implemented as the distinction between `blur` and `focusout` (i.e. `blur` of the navigation menu or its parent, but not _within_ the same wrapper). See also:

- https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event
- https://www.npmjs.com/package/receptor

### PR DESCRIPTION
**Pull request by mejiaj**
## Preview
[Header preview →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-nav-actions/components/detail/header--default.html)

## Description

**Close navigation with escape key.** Mobile menu closes and resets on escape key. On larger screen sizes escape closes any active dropdowns. Closes #3396.

**Dropdowns close on focusout.** Tabbing away from primary navigation now closes any active dropdown. Closes #3528.

## Additional information

- Added test cases in navigation.spec.js
- Updated navigation.js to accept `Esc` key to close nav and dropdowns
- Updated navigation.js to close active dropdown on focusout

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

File: src/js/components/navigation.js [hunk 1]
```diff
@@ -79,6 +88,10 @@ const resize = () => {
 
 const onMenuClose = () => navigation.toggleNav.call(navigation, false);
 const hideActiveNavDropdown = () => {
+  if (!navActive) {
```
Comment (mejiaj) [inline src/js/components/navigation.js:91]: This check used to be in line 91, 96, and 107. Moved it to `hideActiveNavDropdown()` instead, so it checks when the function is called.

File: src/js/components/navigation.js [hunk 2]
```diff
@@ -129,6 +137,18 @@ navigation = behavior(
...
     },
+    keydown: {
+      [BODY]: keymap({ Escape: hideActiveNavDropdown }),
+    },
+    focusout: {
+      [NAV_PRIMARY](event) {
+        const nav = event.target.closest(NAV_PRIMARY);
+
+        if (!nav.contains(event.relatedTarget)) {
+          hideActiveNavDropdown();
```
Comment (mejiaj) [inline src/js/components/navigation.js:148]: Created a new selector in `NAV_PRIMARY` because `NAV` can contain other elements that **aren't** part of the primary navigation menu.

**Comment by scottqueen-bixal** [comment]
Functionality working as expected.

However seeing a few errors in our test run,

Stylelint
https://app.circleci.com/pipelines/github/uswds/uswds/2734/workflows/9c74dbbb-8445-4c36-8e54-b27b31c1effa/jobs/7126?invite=true#step-109-18

Spec
https://app.circleci.com/pipelines/github/uswds/uswds/2734/workflows/9c74dbbb-8445-4c36-8e54-b27b31c1effa/jobs/7126?invite=true#step-109-1141

File: src/js/components/navigation.js [hunk 3]
```diff
@@ -129,6 +137,18 @@ navigation = behavior(
         }
       },
     },
+    keydown: {
+      [NAV_PRIMARY]: keymap({ Escape: hideActiveNavDropdown }),
```
Comment (mejiaj) [inline src/js/components/navigation.js:141]: Switched this from `BODY` to avoid conflicts with other potential functionality.

File: spec/unit/navigation/navigation.spec.js [hunk 4]
```diff
@@ -114,6 +133,19 @@ describe("navigation toggle", () => {
     assert.strictEqual(accordionButton.getAttribute("aria-expanded"), "false");
   });
 
+  it("collapses dropdowns when the Escape key is hit", () => {
```
Comment (mejiaj) [inline spec/unit/navigation/navigation.spec.js:136]: Unit test is now more specific. When you open a dropdown it should close on <kbd>Esc</kbd>.

**Comment by mejiaj** [comment]
I'm able to reproduce the unit test issue locally. Will need to research further because it's also pointing to modal js, not sure why.

File: src/js/components/navigation.js (hunk 3 above)
Comment (aduth) [inline src/js/components/navigation.js:141]: Should focus be managed explicitly when <kbd>Escape</kbd> is pressed when focused on one of the submenu items? Similar to how the modal works, and based on related guidance here:

https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html#kbd2_label

>`Escape`
>- Closes submenu.
>- **Moves focus to parent menubar item.**

File: spec/unit/navigation/navigation.spec.js [hunk 5]
```diff
@@ -7,6 +7,25 @@ const accordion = require("../../../src/js/components/accordion");
 
 const TEMPLATE = fs.readFileSync(path.join(__dirname, "template.html"));
 
+const EVENTS = {
```
Comment (aduth) [inline spec/unit/navigation/navigation.spec.js:10]: Semi-related to my previous comment, I notice the tests have a lot of these event dispatching helpers. Have y'all considered using a library like [Testing Library](https://testing-library.com/) to simplify this? In my experience, it also helps account for a lot of non-obvious [real-world](https://testing-library.com/docs/guiding-principles) details of events, like how clicking an element would also cause a focus event to be fired.

e.g.

```js
import userEvent from '@testing-library/user-event';

// ...

it("collapses dropdowns when the Escape key is hit", () => {
  userEvent.click(accordionButton);
  userEvent.tab();
  userEvent.keyboard('{escape}');
  assert.strictEqual(document.activeElement, accordionButton);
  assert.strictEqual(accordionButton.getAttribute("aria-expanded"), "false");
});
```

Comment (mejiaj) [reply spec/unit/navigation/navigation.spec.js:10]: This would definitely be useful and help bring consistency to the codebase. Thanks for the suggestion.

We still have to take a good look at the unit testing library and see if it's still up to par with what's needed. We've talked about incorporating cypress in the past.

**Review by thisisdano — APPROVED** [review]
:shipit: 🚀 💯
